title: A simple programmer

include: [_pages]


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: _sass

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /blog/:year/:month/:day/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      permalink: /:title/